### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/FusionHelper#1]
Hi, @eduardorasgado , how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
Sure bro! It is a help desk for companies, it is to report hardware or software incidents in different working spaces inside your business headquaters, those are notified to tech team and they can attent to those incidents properly, having a track of those movements.
